import { Book } from '../core/dto/book.interface';

/** Seed data mirroring the so the board isn't empty on first load. */
export const SEED_BOOKS: readonly Book[] = [
  {
    id: 'seed-1',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    status: 'to-read',
    dateStarted: null,
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
  {
    id: 'seed-2',
    title: 'Some People Needs a Killing',
    author: 'Patricia Evangelista',
    status: 'in-progress',
    dateStarted: '2026-07-07',
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
  {
    id: 'seed-3',
    title: 'Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    status: 'finished',
    dateStarted: '2026-03-07',
    dateFinished: '2026-07-01',
    dateDropped: null,
    rating: 4,
    review:
      "A dazzling, emotionally ruthless story about ambition, love, and the lies we tell to survive fame. The reveal hits like a gut punch, and the central romance is one of the most quietly devastating I've read.",
  },
  {
    id: 'seed-4',
    title: 'It Ends With Us',
    author: 'Colleen Hoover',
    status: 'dropped',
    dateStarted: '2026-06-01',
    dateFinished: null,
    dateDropped: '2026-07-07',
    rating: null,
    review: null,
  },
  {
    id: 'seed-5',
    title: 'A Little Prince',
    author: 'Antoine de Saint-Exupéry',
    status: 'to-read',
    dateStarted: null,
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
  {
    id: 'seed-6',
    title: 'The Song of Achilles',
    author: 'Madelline Miller',
    status: 'to-read',
    dateStarted: null,
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
  {
    id: 'seed-7',
    title: 'The Vegetarian',
    author: 'Han Kang',
    status: 'to-read',
    dateStarted: null,
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
  {
    id: 'seed-8',
    title: 'The Lady in the Lake',
    author: 'Raymond Chandler',
    status: 'to-read',
    dateStarted: null,
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
  {
    id: 'seed-9',
    title: 'Only Dull People Are Brilliant at Breakfast',
    author: 'Oscar Wilde',
    status: 'to-read',
    dateStarted: null,
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
  {
    id: 'seed-10',
    title: 'Heated Rivalry',
    author: 'Rachel Reid',
    status: 'to-read',
    dateStarted: null,
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
  {
    id: 'seed-11',
    title: 'East of Eden',
    author: 'John Steinbeck',
    status: 'to-read',
    dateStarted: null,
    dateFinished: null,
    dateDropped: null,
    rating: null,
    review: null,
  },
];